// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif


RcppExport SEXP _rcpp_module_boot_stan_fit4model_misreport_aux_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4model_misreport_cmp_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4model_misreport_doublelist_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4model_misreport_infonorm_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4model_misreport_noaux_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4model_outcome_aux_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4model_outcome_cmp_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4model_outcome_doublelist_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4model_outcome_infonorm_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4model_outcome_noaux_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4model_predict_aux_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4model_predict_aux_linear_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4model_predict_cmp_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4model_predict_cmp_linear_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4model_predict_doublelist_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4model_predict_doublelist_linear_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4model_predict_infonorm_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4model_predict_infonorm_linear_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4model_predict_noaux_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4model_predict_noaux_linear_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_stan_fit4model_misreport_aux_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4model_misreport_aux_mod, 0},
    {"_rcpp_module_boot_stan_fit4model_misreport_cmp_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4model_misreport_cmp_mod, 0},
    {"_rcpp_module_boot_stan_fit4model_misreport_doublelist_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4model_misreport_doublelist_mod, 0},
    {"_rcpp_module_boot_stan_fit4model_misreport_infonorm_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4model_misreport_infonorm_mod, 0},
    {"_rcpp_module_boot_stan_fit4model_misreport_noaux_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4model_misreport_noaux_mod, 0},
    {"_rcpp_module_boot_stan_fit4model_outcome_aux_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4model_outcome_aux_mod, 0},
    {"_rcpp_module_boot_stan_fit4model_outcome_cmp_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4model_outcome_cmp_mod, 0},
    {"_rcpp_module_boot_stan_fit4model_outcome_doublelist_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4model_outcome_doublelist_mod, 0},
    {"_rcpp_module_boot_stan_fit4model_outcome_infonorm_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4model_outcome_infonorm_mod, 0},
    {"_rcpp_module_boot_stan_fit4model_outcome_noaux_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4model_outcome_noaux_mod, 0},
    {"_rcpp_module_boot_stan_fit4model_predict_aux_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4model_predict_aux_mod, 0},
    {"_rcpp_module_boot_stan_fit4model_predict_aux_linear_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4model_predict_aux_linear_mod, 0},
    {"_rcpp_module_boot_stan_fit4model_predict_cmp_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4model_predict_cmp_mod, 0},
    {"_rcpp_module_boot_stan_fit4model_predict_cmp_linear_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4model_predict_cmp_linear_mod, 0},
    {"_rcpp_module_boot_stan_fit4model_predict_doublelist_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4model_predict_doublelist_mod, 0},
    {"_rcpp_module_boot_stan_fit4model_predict_doublelist_linear_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4model_predict_doublelist_linear_mod, 0},
    {"_rcpp_module_boot_stan_fit4model_predict_infonorm_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4model_predict_infonorm_mod, 0},
    {"_rcpp_module_boot_stan_fit4model_predict_infonorm_linear_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4model_predict_infonorm_linear_mod, 0},
    {"_rcpp_module_boot_stan_fit4model_predict_noaux_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4model_predict_noaux_mod, 0},
    {"_rcpp_module_boot_stan_fit4model_predict_noaux_linear_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4model_predict_noaux_linear_mod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_bayeslist(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
