// Generated by rstantools.  Do not edit by hand.

/*
    bayeslist is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    bayeslist is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with bayeslist.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_model_misreport_aux_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 91> locations_array__ =
  {" (found before start of program)",
  " (in 'model_misreport_aux', line 53, column 1 to column 16)",
  " (in 'model_misreport_aux', line 54, column 1 to column 17)",
  " (in 'model_misreport_aux', line 55, column 1 to column 18)",
  " (in 'model_misreport_aux', line 56, column 1 to column 14)",
  " (in 'model_misreport_aux', line 57, column 1 to column 10)",
  " (in 'model_misreport_aux', line 58, column 1 to column 10)",
  " (in 'model_misreport_aux', line 59, column 1 to column 33)",
  " (in 'model_misreport_aux', line 60, column 1 to column 23)",
  " (in 'model_misreport_aux', line 64, column 1 to column 23)",
  " (in 'model_misreport_aux', line 65, column 1 to column 23)",
  " (in 'model_misreport_aux', line 66, column 1 to column 22)",
  " (in 'model_misreport_aux', line 67, column 1 to column 22)",
  " (in 'model_misreport_aux', line 68, column 1 to column 25)",
  " (in 'model_misreport_aux', line 69, column 1 to column 21)",
  " (in 'model_misreport_aux', line 70, column 1 to column 21)",
  " (in 'model_misreport_aux', line 72, column 2 to column 70)",
  " (in 'model_misreport_aux', line 71, column 16 to line 73, column 2)",
  " (in 'model_misreport_aux', line 71, column 1 to line 73, column 2)",
  " (in 'model_misreport_aux', line 88, column 3 to column 15)",
  " (in 'model_misreport_aux', line 87, column 9 to line 89, column 3)",
  " (in 'model_misreport_aux', line 86, column 3 to column 211)",
  " (in 'model_misreport_aux', line 85, column 57 to line 87, column 3)",
  " (in 'model_misreport_aux', line 85, column 9 to line 89, column 3)",
  " (in 'model_misreport_aux', line 84, column 3 to column 374)",
  " (in 'model_misreport_aux', line 83, column 46 to line 85, column 3)",
  " (in 'model_misreport_aux', line 83, column 9 to line 89, column 3)",
  " (in 'model_misreport_aux', line 82, column 3 to column 202)",
  " (in 'model_misreport_aux', line 81, column 63 to line 83, column 3)",
  " (in 'model_misreport_aux', line 81, column 9 to line 89, column 3)",
  " (in 'model_misreport_aux', line 80, column 3 to column 150)",
  " (in 'model_misreport_aux', line 79, column 59 to line 81, column 3)",
  " (in 'model_misreport_aux', line 79, column 9 to line 89, column 3)",
  " (in 'model_misreport_aux', line 78, column 3 to column 197)",
  " (in 'model_misreport_aux', line 77, column 46 to line 79, column 3)",
  " (in 'model_misreport_aux', line 77, column 9 to line 89, column 3)",
  " (in 'model_misreport_aux', line 76, column 3 to column 359)",
  " (in 'model_misreport_aux', line 75, column 38 to line 77, column 3)",
  " (in 'model_misreport_aux', line 75, column 2 to line 89, column 3)",
  " (in 'model_misreport_aux', line 74, column 15 to line 92, column 2)",
  " (in 'model_misreport_aux', line 74, column 1 to line 92, column 2)",
  " (in 'model_misreport_aux', line 39, column 1 to column 7)",
  " (in 'model_misreport_aux', line 40, column 1 to column 7)",
  " (in 'model_misreport_aux', line 41, column 18 to column 19)",
  " (in 'model_misreport_aux', line 41, column 1 to column 21)",
  " (in 'model_misreport_aux', line 42, column 1 to column 7)",
  " (in 'model_misreport_aux', line 43, column 8 to column 9)",
  " (in 'model_misreport_aux', line 43, column 10 to column 11)",
  " (in 'model_misreport_aux', line 43, column 1 to column 15)",
  " (in 'model_misreport_aux', line 44, column 11 to column 12)",
  " (in 'model_misreport_aux', line 44, column 1 to column 14)",
  " (in 'model_misreport_aux', line 45, column 12 to column 13)",
  " (in 'model_misreport_aux', line 45, column 1 to column 15)",
  " (in 'model_misreport_aux', line 46, column 1 to column 7)",
  " (in 'model_misreport_aux', line 47, column 8 to column 9)",
  " (in 'model_misreport_aux', line 47, column 1 to column 11)",
  " (in 'model_misreport_aux', line 48, column 7 to column 8)",
  " (in 'model_misreport_aux', line 48, column 1 to column 10)",
  " (in 'model_misreport_aux', line 53, column 8 to column 9)",
  " (in 'model_misreport_aux', line 54, column 8 to column 9)",
  " (in 'model_misreport_aux', line 55, column 8 to column 9)",
  " (in 'model_misreport_aux', line 4, column 2 to column 31)",
  " (in 'model_misreport_aux', line 3, column 16 to line 5, column 2)",
  " (in 'model_misreport_aux', line 7, column 2 to column 31)",
  " (in 'model_misreport_aux', line 6, column 16 to line 8, column 2)",
  " (in 'model_misreport_aux', line 10, column 2 to column 45)",
  " (in 'model_misreport_aux', line 9, column 46 to line 11, column 2)",
  " (in 'model_misreport_aux', line 13, column 2 to column 45)",
  " (in 'model_misreport_aux', line 12, column 46 to line 14, column 2)",
  " (in 'model_misreport_aux', line 16, column 4 to column 14)",
  " (in 'model_misreport_aux', line 17, column 4 to column 14)",
  " (in 'model_misreport_aux', line 20, column 8 to column 26)",
  " (in 'model_misreport_aux', line 19, column 6 to line 20, column 26)",
  " (in 'model_misreport_aux', line 18, column 4 to line 20, column 26)",
  " (in 'model_misreport_aux', line 21, column 6 to column 19)",
  " (in 'model_misreport_aux', line 15, column 39 to line 22, column 3)",
  " (in 'model_misreport_aux', line 24, column 4 to column 11)",
  " (in 'model_misreport_aux', line 25, column 11 to column 33)",
  " (in 'model_misreport_aux', line 25, column 34 to column 35)",
  " (in 'model_misreport_aux', line 25, column 4 to column 41)",
  " (in 'model_misreport_aux', line 26, column 4 to column 11)",
  " (in 'model_misreport_aux', line 30, column 8 to column 30)",
  " (in 'model_misreport_aux', line 29, column 22 to line 31, column 8)",
  " (in 'model_misreport_aux', line 29, column 7 to line 31, column 8)",
  " (in 'model_misreport_aux', line 32, column 8 to column 18)",
  " (in 'model_misreport_aux', line 28, column 28 to line 33, column 7)",
  " (in 'model_misreport_aux', line 28, column 6 to line 33, column 7)",
  " (in 'model_misreport_aux', line 27, column 27 to line 34, column 5)",
  " (in 'model_misreport_aux', line 27, column 4 to line 34, column 5)",
  " (in 'model_misreport_aux', line 35, column 4 to column 15)",
  " (in 'model_misreport_aux', line 23, column 62 to line 36, column 3)"};
template <typename T0__,
          stan::require_all_t<stan::is_stan_scalar<T0__>>* = nullptr>
stan::promote_args_t<T0__> gd(const T0__& p, std::ostream* pstream__);
template <typename T0__,
          stan::require_all_t<stan::is_stan_scalar<T0__>>* = nullptr>
stan::promote_args_t<T0__> jd(const T0__& p, std::ostream* pstream__);
template <typename T2__, typename T3__,
          stan::require_all_t<stan::is_stan_scalar<T2__>,
                              stan::is_stan_scalar<T3__>>* = nullptr>
stan::promote_args_t<T2__, T3__>
h0d(const int& y, const int& J, const T2__& alpha, const T3__& beta,
    std::ostream* pstream__);
template <typename T2__, typename T3__,
          stan::require_all_t<stan::is_stan_scalar<T2__>,
                              stan::is_stan_scalar<T3__>>* = nullptr>
stan::promote_args_t<T2__, T3__>
h1d(const int& y, const int& J, const T2__& alpha, const T3__& beta,
    std::ostream* pstream__);
int
group_size(const std::vector<int>& ref, const int& value, std::ostream*
           pstream__);
template <typename T0__,
          stan::require_all_t<stan::is_eigen_matrix_dynamic<T0__>,
                              stan::is_vt_not_complex<T0__>>* = nullptr>
Eigen::Matrix<stan::promote_args_t<stan::base_type_t<T0__>>,-1,-1>
subset_matrix(const T0__& y_arg__, const int& k, const std::vector<int>& ref,
              const int& value, std::ostream* pstream__);
template <typename T0__, stan::require_all_t<stan::is_stan_scalar<T0__>>*>
stan::promote_args_t<T0__> gd(const T0__& p, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__>;
  int current_statement__ = 0;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 61;
    return stan::math::binomial_lpmf<false>(1, 1, p);
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <typename T0__, stan::require_all_t<stan::is_stan_scalar<T0__>>*>
stan::promote_args_t<T0__> jd(const T0__& p, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__>;
  int current_statement__ = 0;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 63;
    return stan::math::binomial_lpmf<false>(1, 1, p);
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <typename T2__, typename T3__,
          stan::require_all_t<stan::is_stan_scalar<T2__>,
                              stan::is_stan_scalar<T3__>>*>
stan::promote_args_t<T2__, T3__>
h0d(const int& y, const int& J, const T2__& alpha, const T3__& beta,
    std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T2__, T3__>;
  int current_statement__ = 0;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 65;
    return stan::math::beta_binomial_lpmf<false>(y, J, alpha, beta);
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <typename T2__, typename T3__,
          stan::require_all_t<stan::is_stan_scalar<T2__>,
                              stan::is_stan_scalar<T3__>>*>
stan::promote_args_t<T2__, T3__>
h1d(const int& y, const int& J, const T2__& alpha, const T3__& beta,
    std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T2__, T3__>;
  int current_statement__ = 0;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 67;
    return stan::math::beta_binomial_lpmf<false>(y, J, alpha, beta);
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
int
group_size(const std::vector<int>& ref, const int& value, std::ostream*
           pstream__) {
  using local_scalar_t__ = double;
  int current_statement__ = 0;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    int count = std::numeric_limits<int>::min();
    current_statement__ = 70;
    count = 0;
    current_statement__ = 73;
    for (int ii = 1; ii <= stan::math::size(ref); ++ii) {
      current_statement__ = 72;
      if (stan::math::logical_eq(
            stan::model::rvalue(ref, "ref", stan::model::index_uni(ii)),
            value)) {
        current_statement__ = 71;
        count = (count + 1);
      }
    }
    current_statement__ = 74;
    return count;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <typename T0__,
          stan::require_all_t<stan::is_eigen_matrix_dynamic<T0__>,
                              stan::is_vt_not_complex<T0__>>*>
Eigen::Matrix<stan::promote_args_t<stan::base_type_t<T0__>>,-1,-1>
subset_matrix(const T0__& y_arg__, const int& k, const std::vector<int>& ref,
              const int& value, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<stan::base_type_t<T0__>>;
  int current_statement__ = 0;
  const auto& y = stan::math::to_ref(y_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    int jj = std::numeric_limits<int>::min();
    current_statement__ = 77;
    stan::math::validate_non_negative_index("res", "group_size(ref, value)",
      group_size(ref, value, pstream__));
    current_statement__ = 78;
    stan::math::validate_non_negative_index("res", "k", k);
    Eigen::Matrix<local_scalar_t__,-1,-1> res =
      Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(group_size(ref, value,
                                                        pstream__), k,
        DUMMY_VAR__);
    current_statement__ = 80;
    jj = 1;
    current_statement__ = 88;
    for (int ii = 1; ii <= stan::math::size(ref); ++ii) {
      current_statement__ = 86;
      if (stan::math::logical_eq(
            stan::model::rvalue(ref, "ref", stan::model::index_uni(ii)),
            value)) {
        current_statement__ = 83;
        for (int kk = 1; kk <= k; ++kk) {
          current_statement__ = 81;
          stan::model::assign(res,
            stan::model::rvalue(y, "y", stan::model::index_uni(ii),
              stan::model::index_uni(kk)), "assigning variable res",
            stan::model::index_uni(jj), stan::model::index_uni(kk));
        }
        current_statement__ = 84;
        jj = (jj + 1);
      }
    }
    current_statement__ = 89;
    return res;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
#include <stan_meta_header.hpp>
class model_model_misreport_aux final : public model_base_crtp<model_model_misreport_aux> {
private:
  int N;
  int J;
  std::vector<int> Y;
  int K;
  Eigen::Matrix<double,-1,-1> X_data__;
  std::vector<int> treat;
  std::vector<int> direct;
  int G;
  std::vector<double> h;
  std::vector<int> g;
  Eigen::Map<Eigen::Matrix<double,-1,-1>> X{nullptr, 0, 0};
public:
  ~model_model_misreport_aux() {}
  model_model_misreport_aux(stan::io::var_context& context__, unsigned int
                            random_seed__ = 0, std::ostream*
                            pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_model_misreport_aux_namespace::model_model_misreport_aux";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 41;
      context__.validate_dims("data initialization", "N", "int",
        std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      current_statement__ = 41;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 42;
      context__.validate_dims("data initialization", "J", "int",
        std::vector<size_t>{});
      J = std::numeric_limits<int>::min();
      current_statement__ = 42;
      J = context__.vals_i("J")[(1 - 1)];
      current_statement__ = 43;
      stan::math::validate_non_negative_index("Y", "N", N);
      current_statement__ = 44;
      context__.validate_dims("data initialization", "Y", "int",
        std::vector<size_t>{static_cast<size_t>(N)});
      Y = std::vector<int>(N, std::numeric_limits<int>::min());
      current_statement__ = 44;
      Y = context__.vals_i("Y");
      current_statement__ = 44;
      stan::math::check_greater_or_equal(function__, "Y", Y, 0);
      current_statement__ = 45;
      context__.validate_dims("data initialization", "K", "int",
        std::vector<size_t>{});
      K = std::numeric_limits<int>::min();
      current_statement__ = 45;
      K = context__.vals_i("K")[(1 - 1)];
      current_statement__ = 46;
      stan::math::validate_non_negative_index("X", "N", N);
      current_statement__ = 47;
      stan::math::validate_non_negative_index("X", "K", K);
      current_statement__ = 48;
      context__.validate_dims("data initialization", "X", "double",
        std::vector<size_t>{static_cast<size_t>(N), static_cast<size_t>(K)});
      X_data__ = Eigen::Matrix<double,-1,-1>::Constant(N, K,
                   std::numeric_limits<double>::quiet_NaN());
      new (&X) Eigen::Map<Eigen::Matrix<double,-1,-1>>(X_data__.data(), N, K);
      {
        std::vector<local_scalar_t__> X_flat__;
        current_statement__ = 48;
        X_flat__ = context__.vals_r("X");
        current_statement__ = 48;
        pos__ = 1;
        current_statement__ = 48;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 48;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 48;
            stan::model::assign(X, X_flat__[(pos__ - 1)],
              "assigning variable X", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 48;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 49;
      stan::math::validate_non_negative_index("treat", "N", N);
      current_statement__ = 50;
      context__.validate_dims("data initialization", "treat", "int",
        std::vector<size_t>{static_cast<size_t>(N)});
      treat = std::vector<int>(N, std::numeric_limits<int>::min());
      current_statement__ = 50;
      treat = context__.vals_i("treat");
      current_statement__ = 51;
      stan::math::validate_non_negative_index("direct", "N", N);
      current_statement__ = 52;
      context__.validate_dims("data initialization", "direct", "int",
        std::vector<size_t>{static_cast<size_t>(N)});
      direct = std::vector<int>(N, std::numeric_limits<int>::min());
      current_statement__ = 52;
      direct = context__.vals_i("direct");
      current_statement__ = 53;
      context__.validate_dims("data initialization", "G", "int",
        std::vector<size_t>{});
      G = std::numeric_limits<int>::min();
      current_statement__ = 53;
      G = context__.vals_i("G")[(1 - 1)];
      current_statement__ = 54;
      stan::math::validate_non_negative_index("h", "G", G);
      current_statement__ = 55;
      context__.validate_dims("data initialization", "h", "double",
        std::vector<size_t>{static_cast<size_t>(G)});
      h = std::vector<double>(G, std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 55;
      h = context__.vals_r("h");
      current_statement__ = 56;
      stan::math::validate_non_negative_index("g", "N", N);
      current_statement__ = 57;
      context__.validate_dims("data initialization", "g", "int",
        std::vector<size_t>{static_cast<size_t>(N)});
      g = std::vector<int>(N, std::numeric_limits<int>::min());
      current_statement__ = 57;
      g = context__.vals_i("g");
      current_statement__ = 58;
      stan::math::validate_non_negative_index("psi0", "K", K);
      current_statement__ = 59;
      stan::math::validate_non_negative_index("delta", "K", K);
      current_statement__ = 60;
      stan::math::validate_non_negative_index("gamma0", "K", K);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = K + K + K + 1 + 1 + 1 + 1 + 1;
  }
  inline std::string model_name() const final {
    return "model_model_misreport_aux";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_model_misreport_aux_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<local_scalar_t__,-1,1> psi0 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 1;
      psi0 = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(K);
      Eigen::Matrix<local_scalar_t__,-1,1> delta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 2;
      delta = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(K);
      Eigen::Matrix<local_scalar_t__,-1,1> gamma0 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 3;
      gamma0 = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(K);
      local_scalar_t__ treat_e = DUMMY_VAR__;
      current_statement__ = 4;
      treat_e = in__.template read<local_scalar_t__>();
      local_scalar_t__ U_e = DUMMY_VAR__;
      current_statement__ = 5;
      U_e = in__.template read<local_scalar_t__>();
      local_scalar_t__ Z_e = DUMMY_VAR__;
      current_statement__ = 6;
      Z_e = in__.template read<local_scalar_t__>();
      local_scalar_t__ rho0 = DUMMY_VAR__;
      current_statement__ = 7;
      rho0 = in__.template read_constrain_lub<local_scalar_t__,
               jacobian__>(0, 1, lp__);
      local_scalar_t__ sigma = DUMMY_VAR__;
      current_statement__ = 8;
      sigma = in__.template read_constrain_lb<local_scalar_t__,
                jacobian__>(0, lp__);
      {
        current_statement__ = 9;
        lp_accum__.add(stan::math::cauchy_lpdf<propto__>(sigma, 0, 2.5));
        current_statement__ = 10;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(gamma0, 0, 10));
        current_statement__ = 11;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(delta, 0, 10));
        current_statement__ = 12;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(psi0, 0, 10));
        current_statement__ = 13;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(treat_e, 0, 10));
        current_statement__ = 14;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(U_e, 0, 10));
        current_statement__ = 15;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(Z_e, 0, 10));
        current_statement__ = 18;
        for (int gg = 1; gg <= G; ++gg) {
          current_statement__ = 16;
          lp_accum__.add(stan::math::normal_lpdf<propto__>(
                           stan::math::logit(
                             stan::model::rvalue(h, "h",
                               stan::model::index_uni(gg))),
                           stan::math::mean(
                             stan::math::multiply(
                               subset_matrix(X, K, g, gg, pstream__), delta)),
                           sigma));
        }
        current_statement__ = 40;
        for (int i = 1; i <= N; ++i) {
          current_statement__ = 38;
          if ((stan::math::primitive_value(
                 stan::math::logical_eq(
                   stan::model::rvalue(treat, "treat",
                     stan::model::index_uni(i)), 0))
              &&
              stan::math::primitive_value(
                stan::math::logical_eq(
                  stan::model::rvalue(direct, "direct",
                    stan::model::index_uni(i)), 0)))) {
            current_statement__ = 36;
            lp_accum__.add(stan::math::log(
                             (((stan::math::exp(
                                  jd(
                                    stan::math::inv_logit(
                                      stan::math::multiply(
                                        stan::model::rvalue(X, "X",
                                          stan::model::index_uni(i),
                                          stan::model::index_omni()), gamma0)),
                                    pstream__)) *
                             stan::math::exp(
                               gd(
                                 stan::math::inv_logit(
                                   stan::math::multiply(
                                     stan::model::rvalue(X, "X",
                                       stan::model::index_uni(i),
                                       stan::model::index_omni()), delta)),
                                 pstream__))) *
                             stan::math::exp(
                               h1d(
                                 stan::model::rvalue(Y, "Y",
                                   stan::model::index_uni(i)), J,
                                 ((stan::math::inv_logit(
                                     ((stan::math::multiply(
                                         stan::model::rvalue(X, "X",
                                           stan::model::index_uni(i),
                                           stan::model::index_omni()), psi0)
                                     + Z_e) + U_e)) * (1 - rho0)) / rho0),
                                 (((1 -
                                 stan::math::inv_logit(
                                   ((stan::math::multiply(
                                       stan::model::rvalue(X, "X",
                                         stan::model::index_uni(i),
                                         stan::model::index_omni()), psi0) +
                                   Z_e) + U_e))) * (1 - rho0)) / rho0),
                                 pstream__))) + ((1 -
                             stan::math::exp(
                               gd(
                                 stan::math::inv_logit(
                                   stan::math::multiply(
                                     stan::model::rvalue(X, "X",
                                       stan::model::index_uni(i),
                                       stan::model::index_omni()), delta)),
                                 pstream__))) *
                             stan::math::exp(
                               h0d(
                                 stan::model::rvalue(Y, "Y",
                                   stan::model::index_uni(i)), J,
                                 ((stan::math::inv_logit(
                                     stan::math::multiply(
                                       stan::model::rvalue(X, "X",
                                         stan::model::index_uni(i),
                                         stan::model::index_omni()), psi0)) *
                                 (1 - rho0)) / rho0), (((1 -
                                 stan::math::inv_logit(
                                   stan::math::multiply(
                                     stan::model::rvalue(X, "X",
                                       stan::model::index_uni(i),
                                       stan::model::index_omni()), psi0))) *
                                 (1 - rho0)) / rho0), pstream__))))));
          } else {
            current_statement__ = 35;
            if ((stan::math::primitive_value(
                   stan::math::logical_eq(
                     stan::model::rvalue(treat, "treat",
                       stan::model::index_uni(i)), 0))
                &&
                stan::math::primitive_value(
                  stan::math::logical_eq(
                    stan::model::rvalue(direct, "direct",
                      stan::model::index_uni(i)), 1)))) {
              current_statement__ = 33;
              lp_accum__.add(((stan::math::log((1 -
                                 stan::math::exp(
                                   jd(
                                     stan::math::inv_logit(
                                       stan::math::multiply(
                                         stan::model::rvalue(X, "X",
                                           stan::model::index_uni(i),
                                           stan::model::index_omni()), gamma0)),
                                     pstream__)))) +
                gd(
                  stan::math::inv_logit(
                    stan::math::multiply(
                      stan::model::rvalue(X, "X", stan::model::index_uni(i),
                        stan::model::index_omni()), delta)), pstream__)) +
                h1d(stan::model::rvalue(Y, "Y", stan::model::index_uni(i)),
                  J,
                  ((stan::math::inv_logit(
                      (stan::math::multiply(
                         stan::model::rvalue(X, "X",
                           stan::model::index_uni(i),
                           stan::model::index_omni()), psi0) + Z_e)) * (1 -
                  rho0)) / rho0), (((1 -
                  stan::math::inv_logit(
                    (stan::math::multiply(
                       stan::model::rvalue(X, "X", stan::model::index_uni(i),
                         stan::model::index_omni()), psi0) + Z_e))) * (1 -
                  rho0)) / rho0), pstream__)));
            } else {
              current_statement__ = 32;
              if ((stan::math::primitive_value(
                     (stan::math::primitive_value(
                        stan::math::logical_eq(
                          stan::model::rvalue(treat, "treat",
                            stan::model::index_uni(i)), 1)) &&
                     stan::math::primitive_value(
                       stan::math::logical_eq(
                         stan::model::rvalue(direct, "direct",
                           stan::model::index_uni(i)), 0))))
                  &&
                  stan::math::primitive_value(
                    stan::math::logical_eq(
                      stan::model::rvalue(Y, "Y", stan::model::index_uni(i)),
                      0)))) {
                current_statement__ = 30;
                lp_accum__.add((stan::math::log((1 -
                                  stan::math::exp(
                                    gd(
                                      stan::math::inv_logit(
                                        stan::math::multiply(
                                          stan::model::rvalue(X, "X",
                                            stan::model::index_uni(i),
                                            stan::model::index_omni()), delta)),
                                      pstream__)))) +
                  h0d(0, J,
                    ((stan::math::inv_logit(
                        stan::math::multiply(
                          stan::model::rvalue(X, "X",
                            stan::model::index_uni(i),
                            stan::model::index_omni()), psi0)) * (1 - rho0))
                    / rho0), (((1 -
                    stan::math::inv_logit(
                      stan::math::multiply(
                        stan::model::rvalue(X, "X",
                          stan::model::index_uni(i),
                          stan::model::index_omni()), psi0))) * (1 - rho0)) /
                    rho0), pstream__)));
              } else {
                current_statement__ = 29;
                if ((stan::math::primitive_value(
                       (stan::math::primitive_value(
                          stan::math::logical_eq(
                            stan::model::rvalue(treat, "treat",
                              stan::model::index_uni(i)), 1)) &&
                       stan::math::primitive_value(
                         stan::math::logical_eq(
                           stan::model::rvalue(direct, "direct",
                             stan::model::index_uni(i)), 0))))
                    &&
                    stan::math::primitive_value(
                      stan::math::logical_eq(
                        stan::model::rvalue(Y, "Y", stan::model::index_uni(i)),
                        (J + 1))))) {
                  current_statement__ = 27;
                  lp_accum__.add(((jd(
                                     stan::math::inv_logit(
                                       (stan::math::multiply(
                                          stan::model::rvalue(X, "X",
                                            stan::model::index_uni(i),
                                            stan::model::index_omni()),
                                          gamma0) + treat_e)), pstream__) +
                    gd(
                      stan::math::inv_logit(
                        stan::math::multiply(
                          stan::model::rvalue(X, "X",
                            stan::model::index_uni(i),
                            stan::model::index_omni()), delta)), pstream__))
                    +
                    h1d(J, J,
                      ((stan::math::inv_logit(
                          ((stan::math::multiply(
                              stan::model::rvalue(X, "X",
                                stan::model::index_uni(i),
                                stan::model::index_omni()), psi0) + Z_e) +
                          U_e)) * (1 - rho0)) / rho0), (((1 -
                      stan::math::inv_logit(
                        ((stan::math::multiply(
                            stan::model::rvalue(X, "X",
                              stan::model::index_uni(i),
                              stan::model::index_omni()), psi0) + Z_e) + U_e)))
                      * (1 - rho0)) / rho0), pstream__)));
                } else {
                  current_statement__ = 26;
                  if ((stan::math::primitive_value(
                         stan::math::logical_eq(
                           stan::model::rvalue(treat, "treat",
                             stan::model::index_uni(i)), 1))
                      &&
                      stan::math::primitive_value(
                        stan::math::logical_eq(
                          stan::model::rvalue(direct, "direct",
                            stan::model::index_uni(i)), 0)))) {
                    current_statement__ = 24;
                    lp_accum__.add(stan::math::log(
                                     (((stan::math::exp(
                                          jd(
                                            stan::math::inv_logit(
                                              (stan::math::multiply(
                                                 stan::model::rvalue(X, "X",
                                                   stan::model::index_uni(i),
                                                   stan::model::index_omni()),
                                                 gamma0) + treat_e)),
                                            pstream__)) *
                                     stan::math::exp(
                                       gd(
                                         stan::math::inv_logit(
                                           stan::math::multiply(
                                             stan::model::rvalue(X, "X",
                                               stan::model::index_uni(i),
                                               stan::model::index_omni()),
                                             delta)), pstream__))) *
                                     stan::math::exp(
                                       h1d(
                                         (stan::model::rvalue(Y, "Y",
                                            stan::model::index_uni(i)) - 1),
                                         J,
                                         ((stan::math::inv_logit(
                                             ((stan::math::multiply(
                                                 stan::model::rvalue(X, "X",
                                                   stan::model::index_uni(i),
                                                   stan::model::index_omni()),
                                                 psi0) + Z_e) + U_e)) * (1 -
                                         rho0)) / rho0), (((1 -
                                         stan::math::inv_logit(
                                           ((stan::math::multiply(
                                               stan::model::rvalue(X, "X",
                                                 stan::model::index_uni(i),
                                                 stan::model::index_omni()),
                                               psi0) + Z_e) + U_e))) * (1 -
                                         rho0)) / rho0), pstream__))) + ((1 -
                                     stan::math::exp(
                                       gd(
                                         stan::math::inv_logit(
                                           stan::math::multiply(
                                             stan::model::rvalue(X, "X",
                                               stan::model::index_uni(i),
                                               stan::model::index_omni()),
                                             delta)), pstream__))) *
                                     stan::math::exp(
                                       h0d(
                                         stan::model::rvalue(Y, "Y",
                                           stan::model::index_uni(i)), J,
                                         ((stan::math::inv_logit(
                                             stan::math::multiply(
                                               stan::model::rvalue(X, "X",
                                                 stan::model::index_uni(i),
                                                 stan::model::index_omni()),
                                               psi0)) * (1 - rho0)) / rho0),
                                         (((1 -
                                         stan::math::inv_logit(
                                           stan::math::multiply(
                                             stan::model::rvalue(X, "X",
                                               stan::model::index_uni(i),
                                               stan::model::index_omni()),
                                             psi0))) * (1 - rho0)) / rho0),
                                         pstream__))))));
                  } else {
                    current_statement__ = 23;
                    if ((stan::math::primitive_value(
                           (stan::math::primitive_value(
                              stan::math::logical_eq(
                                stan::model::rvalue(treat, "treat",
                                  stan::model::index_uni(i)), 1)) &&
                           stan::math::primitive_value(
                             stan::math::logical_eq(
                               stan::model::rvalue(direct, "direct",
                                 stan::model::index_uni(i)), 1))))
                        &&
                        stan::math::primitive_value(
                          stan::math::logical_gt(
                            stan::model::rvalue(Y, "Y",
                              stan::model::index_uni(i)), 0)))) {
                      current_statement__ = 21;
                      lp_accum__.add(((stan::math::log((1 -
                                         stan::math::exp(
                                           jd(
                                             stan::math::inv_logit(
                                               (stan::math::multiply(
                                                  stan::model::rvalue(X, "X",
                                                    stan::model::index_uni(i),
                                                    stan::model::index_omni()),
                                                  gamma0) + treat_e)),
                                             pstream__)))) +
                        gd(
                          stan::math::inv_logit(
                            stan::math::multiply(
                              stan::model::rvalue(X, "X",
                                stan::model::index_uni(i),
                                stan::model::index_omni()), delta)),
                          pstream__)) +
                        h1d(
                          (stan::model::rvalue(Y, "Y",
                             stan::model::index_uni(i)) - 1), J,
                          ((stan::math::inv_logit(
                              (stan::math::multiply(
                                 stan::model::rvalue(X, "X",
                                   stan::model::index_uni(i),
                                   stan::model::index_omni()), psi0) + Z_e))
                          * (1 - rho0)) / rho0), (((1 -
                          stan::math::inv_logit(
                            (stan::math::multiply(
                               stan::model::rvalue(X, "X",
                                 stan::model::index_uni(i),
                                 stan::model::index_omni()), psi0) + Z_e))) *
                          (1 - rho0)) / rho0), pstream__)));
                    } else {
                      current_statement__ = 19;
                      lp_accum__.add(1);
                    }
                  }
                }
              }
            }
          }
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_model_misreport_aux_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<double,-1,1> psi0 =
        Eigen::Matrix<double,-1,1>::Constant(K,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 1;
      psi0 = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(K);
      Eigen::Matrix<double,-1,1> delta =
        Eigen::Matrix<double,-1,1>::Constant(K,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 2;
      delta = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(K);
      Eigen::Matrix<double,-1,1> gamma0 =
        Eigen::Matrix<double,-1,1>::Constant(K,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 3;
      gamma0 = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(K);
      double treat_e = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 4;
      treat_e = in__.template read<local_scalar_t__>();
      double U_e = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 5;
      U_e = in__.template read<local_scalar_t__>();
      double Z_e = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 6;
      Z_e = in__.template read<local_scalar_t__>();
      double rho0 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 7;
      rho0 = in__.template read_constrain_lub<local_scalar_t__,
               jacobian__>(0, 1, lp__);
      double sigma = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 8;
      sigma = in__.template read_constrain_lb<local_scalar_t__,
                jacobian__>(0, lp__);
      out__.write(psi0);
      out__.write(delta);
      out__.write(gamma0);
      out__.write(treat_e);
      out__.write(U_e);
      out__.write(Z_e);
      out__.write(rho0);
      out__.write(sigma);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> psi0 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 1;
      stan::model::assign(psi0,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(K),
        "assigning variable psi0");
      out__.write(psi0);
      Eigen::Matrix<local_scalar_t__,-1,1> delta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 2;
      stan::model::assign(delta,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(K),
        "assigning variable delta");
      out__.write(delta);
      Eigen::Matrix<local_scalar_t__,-1,1> gamma0 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 3;
      stan::model::assign(gamma0,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(K),
        "assigning variable gamma0");
      out__.write(gamma0);
      local_scalar_t__ treat_e = DUMMY_VAR__;
      current_statement__ = 4;
      treat_e = in__.read<local_scalar_t__>();
      out__.write(treat_e);
      local_scalar_t__ U_e = DUMMY_VAR__;
      current_statement__ = 5;
      U_e = in__.read<local_scalar_t__>();
      out__.write(U_e);
      local_scalar_t__ Z_e = DUMMY_VAR__;
      current_statement__ = 6;
      Z_e = in__.read<local_scalar_t__>();
      out__.write(Z_e);
      local_scalar_t__ rho0 = DUMMY_VAR__;
      current_statement__ = 7;
      rho0 = in__.read<local_scalar_t__>();
      out__.write_free_lub(0, 1, rho0);
      local_scalar_t__ sigma = DUMMY_VAR__;
      current_statement__ = 8;
      sigma = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, sigma);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "psi0", "double",
        std::vector<size_t>{static_cast<size_t>(K)});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "delta", "double",
        std::vector<size_t>{static_cast<size_t>(K)});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "gamma0", "double",
        std::vector<size_t>{static_cast<size_t>(K)});
      current_statement__ = 4;
      context__.validate_dims("parameter initialization", "treat_e",
        "double", std::vector<size_t>{});
      current_statement__ = 5;
      context__.validate_dims("parameter initialization", "U_e", "double",
        std::vector<size_t>{});
      current_statement__ = 6;
      context__.validate_dims("parameter initialization", "Z_e", "double",
        std::vector<size_t>{});
      current_statement__ = 7;
      context__.validate_dims("parameter initialization", "rho0", "double",
        std::vector<size_t>{});
      current_statement__ = 8;
      context__.validate_dims("parameter initialization", "sigma", "double",
        std::vector<size_t>{});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> psi0 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> psi0_flat__;
        current_statement__ = 1;
        psi0_flat__ = context__.vals_r("psi0");
        current_statement__ = 1;
        pos__ = 1;
        current_statement__ = 1;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 1;
          stan::model::assign(psi0, psi0_flat__[(pos__ - 1)],
            "assigning variable psi0", stan::model::index_uni(sym1__));
          current_statement__ = 1;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(psi0);
      Eigen::Matrix<local_scalar_t__,-1,1> delta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> delta_flat__;
        current_statement__ = 2;
        delta_flat__ = context__.vals_r("delta");
        current_statement__ = 2;
        pos__ = 1;
        current_statement__ = 2;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 2;
          stan::model::assign(delta, delta_flat__[(pos__ - 1)],
            "assigning variable delta", stan::model::index_uni(sym1__));
          current_statement__ = 2;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(delta);
      Eigen::Matrix<local_scalar_t__,-1,1> gamma0 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> gamma0_flat__;
        current_statement__ = 3;
        gamma0_flat__ = context__.vals_r("gamma0");
        current_statement__ = 3;
        pos__ = 1;
        current_statement__ = 3;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 3;
          stan::model::assign(gamma0, gamma0_flat__[(pos__ - 1)],
            "assigning variable gamma0", stan::model::index_uni(sym1__));
          current_statement__ = 3;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(gamma0);
      local_scalar_t__ treat_e = DUMMY_VAR__;
      current_statement__ = 4;
      treat_e = context__.vals_r("treat_e")[(1 - 1)];
      out__.write(treat_e);
      local_scalar_t__ U_e = DUMMY_VAR__;
      current_statement__ = 5;
      U_e = context__.vals_r("U_e")[(1 - 1)];
      out__.write(U_e);
      local_scalar_t__ Z_e = DUMMY_VAR__;
      current_statement__ = 6;
      Z_e = context__.vals_r("Z_e")[(1 - 1)];
      out__.write(Z_e);
      local_scalar_t__ rho0 = DUMMY_VAR__;
      current_statement__ = 7;
      rho0 = context__.vals_r("rho0")[(1 - 1)];
      out__.write_free_lub(0, 1, rho0);
      local_scalar_t__ sigma = DUMMY_VAR__;
      current_statement__ = 8;
      sigma = context__.vals_r("sigma")[(1 - 1)];
      out__.write_free_lb(0, sigma);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"psi0", "delta", "gamma0", "treat_e",
                "U_e", "Z_e", "rho0", "sigma"};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{static_cast<
                                                                    size_t>(K)},
                std::vector<size_t>{static_cast<size_t>(K)},
                std::vector<size_t>{static_cast<size_t>(K)},
                std::vector<size_t>{}, std::vector<size_t>{},
                std::vector<size_t>{}, std::vector<size_t>{},
                std::vector<size_t>{}};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      param_names__.emplace_back(std::string() + "psi0" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      param_names__.emplace_back(std::string() + "delta" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      param_names__.emplace_back(std::string() + "gamma0" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "treat_e");
    param_names__.emplace_back(std::string() + "U_e");
    param_names__.emplace_back(std::string() + "Z_e");
    param_names__.emplace_back(std::string() + "rho0");
    param_names__.emplace_back(std::string() + "sigma");
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      param_names__.emplace_back(std::string() + "psi0" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      param_names__.emplace_back(std::string() + "delta" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      param_names__.emplace_back(std::string() + "gamma0" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "treat_e");
    param_names__.emplace_back(std::string() + "U_e");
    param_names__.emplace_back(std::string() + "Z_e");
    param_names__.emplace_back(std::string() + "rho0");
    param_names__.emplace_back(std::string() + "sigma");
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"psi0\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"delta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"gamma0\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"treat_e\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"U_e\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"Z_e\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"rho0\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"psi0\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"delta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"gamma0\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"treat_e\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"U_e\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"Z_e\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"rho0\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((((((K + K) + K) + 1) + 1) + 1) + 1) + 1);
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((((((K + K) + K) + 1) + 1) + 1) + 1) + 1);
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_model_misreport_aux_namespace::model_model_misreport_aux;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_model_misreport_aux_namespace::profiles__;
}
#endif
#endif
