// Generated by rstantools.  Do not edit by hand.

/*
    bayeslist is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    bayeslist is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with bayeslist.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#include <rstan/rstaninc.hpp>
// Code generated by Stan version 2.18.0
#include <stan/model/model_header.hpp>
namespace model_model_misreport_aux_namespace {
using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;
static int current_statement_begin__;
stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "model_model_misreport_aux");
    reader.add_event(117, 115, "end", "model_model_misreport_aux");
    return reader;
}
template <typename T0__>
typename boost::math::tools::promote_args<T0__>::type
gd(const T0__& p, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T0__>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
    int current_statement_begin__ = -1;
    try {
        current_statement_begin__ = 5;
        return stan::math::promote_scalar<fun_return_scalar_t__>(binomial_log(1,1,p));
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}
struct gd_functor__ {
    template <typename T0__>
        typename boost::math::tools::promote_args<T0__>::type
    operator()(const T0__& p, std::ostream* pstream__) const {
        return gd(p, pstream__);
    }
};
template <typename T0__>
typename boost::math::tools::promote_args<T0__>::type
jd(const T0__& p, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T0__>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
    int current_statement_begin__ = -1;
    try {
        current_statement_begin__ = 9;
        return stan::math::promote_scalar<fun_return_scalar_t__>(binomial_log(1,1,p));
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}
struct jd_functor__ {
    template <typename T0__>
        typename boost::math::tools::promote_args<T0__>::type
    operator()(const T0__& p, std::ostream* pstream__) const {
        return jd(p, pstream__);
    }
};
template <typename T2__, typename T3__>
typename boost::math::tools::promote_args<T2__, T3__>::type
h0d(const int& y,
        const int& J,
        const T2__& alpha,
        const T3__& beta, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T2__, T3__>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
    int current_statement_begin__ = -1;
    try {
        current_statement_begin__ = 13;
        return stan::math::promote_scalar<fun_return_scalar_t__>(beta_binomial_log(y,J,alpha,beta));
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}
struct h0d_functor__ {
    template <typename T2__, typename T3__>
        typename boost::math::tools::promote_args<T2__, T3__>::type
    operator()(const int& y,
        const int& J,
        const T2__& alpha,
        const T3__& beta, std::ostream* pstream__) const {
        return h0d(y, J, alpha, beta, pstream__);
    }
};
template <typename T2__, typename T3__>
typename boost::math::tools::promote_args<T2__, T3__>::type
h1d(const int& y,
        const int& J,
        const T2__& alpha,
        const T3__& beta, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T2__, T3__>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
    int current_statement_begin__ = -1;
    try {
        current_statement_begin__ = 17;
        return stan::math::promote_scalar<fun_return_scalar_t__>(beta_binomial_log(y,J,alpha,beta));
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}
struct h1d_functor__ {
    template <typename T2__, typename T3__>
        typename boost::math::tools::promote_args<T2__, T3__>::type
    operator()(const int& y,
        const int& J,
        const T2__& alpha,
        const T3__& beta, std::ostream* pstream__) const {
        return h1d(y, J, alpha, beta, pstream__);
    }
};
int
group_size(const std::vector<int>& ref,
               const int& value, std::ostream* pstream__) {
    typedef double local_scalar_t__;
    typedef int fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
    int current_statement_begin__ = -1;
    try {
        {
        current_statement_begin__ = 21;
        int count(0);
        (void) count;  // dummy to suppress unused var warning
        stan::math::fill(count, std::numeric_limits<int>::min());
        current_statement_begin__ = 22;
        stan::math::assign(count, 0);
        current_statement_begin__ = 23;
        for (int ii = 1; ii <= size(ref); ++ii) {
            current_statement_begin__ = 24;
            if (as_bool(logical_eq(get_base1(ref,ii,"ref",1),value))) {
                current_statement_begin__ = 25;
                stan::math::assign(count, stan::model::deep_copy((count + 1)));
            }
        }
        current_statement_begin__ = 26;
        return stan::math::promote_scalar<fun_return_scalar_t__>(count);
        }
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}
struct group_size_functor__ {
            int
    operator()(const std::vector<int>& ref,
               const int& value, std::ostream* pstream__) const {
        return group_size(ref, value, pstream__);
    }
};
template <typename T0__>
Eigen::Matrix<typename boost::math::tools::promote_args<T0__>::type, Eigen::Dynamic,Eigen::Dynamic>
subset_matrix(const Eigen::Matrix<T0__, Eigen::Dynamic,Eigen::Dynamic>& y,
                  const int& k,
                  const std::vector<int>& ref,
                  const int& value, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T0__>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
    int current_statement_begin__ = -1;
    try {
        {
        current_statement_begin__ = 30;
        int jj(0);
        (void) jj;  // dummy to suppress unused var warning
        stan::math::fill(jj, std::numeric_limits<int>::min());
        current_statement_begin__ = 31;
        validate_non_negative_index("res", "group_size(ref,value, pstream__)", group_size(ref,value, pstream__));
        validate_non_negative_index("res", "k", k);
        Eigen::Matrix<local_scalar_t__,Eigen::Dynamic,Eigen::Dynamic>  res(static_cast<Eigen::VectorXd::Index>(group_size(ref,value, pstream__)),static_cast<Eigen::VectorXd::Index>(k));
        (void) res;  // dummy to suppress unused var warning
        stan::math::initialize(res, DUMMY_VAR__);
        stan::math::fill(res,DUMMY_VAR__);
        current_statement_begin__ = 32;
        stan::math::assign(jj, 1);
        current_statement_begin__ = 33;
        for (int ii = 1; ii <= size(ref); ++ii) {
            current_statement_begin__ = 34;
            if (as_bool(logical_eq(get_base1(ref,ii,"ref",1),value))) {
                current_statement_begin__ = 35;
                for (int kk = 1; kk <= k; ++kk) {
                    current_statement_begin__ = 36;
                    stan::model::assign(res, 
                                stan::model::cons_list(stan::model::index_uni(jj), stan::model::cons_list(stan::model::index_uni(kk), stan::model::nil_index_list())), 
                                get_base1(y,ii,kk,"y",1), 
                                "assigning variable res");
                }
                current_statement_begin__ = 38;
                stan::math::assign(jj, stan::model::deep_copy((jj + 1)));
            }
        }
        current_statement_begin__ = 41;
        return stan::math::promote_scalar<fun_return_scalar_t__>(res);
        }
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}
struct subset_matrix_functor__ {
    template <typename T0__>
        Eigen::Matrix<typename boost::math::tools::promote_args<T0__>::type, Eigen::Dynamic,Eigen::Dynamic>
    operator()(const Eigen::Matrix<T0__, Eigen::Dynamic,Eigen::Dynamic>& y,
                  const int& k,
                  const std::vector<int>& ref,
                  const int& value, std::ostream* pstream__) const {
        return subset_matrix(y, k, ref, value, pstream__);
    }
};
#include <stan_meta_header.hpp>
class model_model_misreport_aux : public prob_grad {
private:
    int N;
    int J;
    vector<int> Y;
    int K;
    matrix_d X;
    vector<int> treat;
    vector<int> direct;
    int G;
    vector<double> h;
    vector<int> g;
public:
    model_model_misreport_aux(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        ctor_body(context__, 0, pstream__);
    }
    model_model_misreport_aux(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        ctor_body(context__, random_seed__, pstream__);
    }
    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        typedef double local_scalar_t__;
        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning
        current_statement_begin__ = -1;
        static const char* function__ = "model_model_misreport_aux_namespace::model_model_misreport_aux";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        // initialize member variables
        try {
            current_statement_begin__ = 48;
            context__.validate_dims("data initialization", "N", "int", context__.to_vec());
            N = int(0);
            vals_i__ = context__.vals_i("N");
            pos__ = 0;
            N = vals_i__[pos__++];
            current_statement_begin__ = 49;
            context__.validate_dims("data initialization", "J", "int", context__.to_vec());
            J = int(0);
            vals_i__ = context__.vals_i("J");
            pos__ = 0;
            J = vals_i__[pos__++];
            current_statement_begin__ = 50;
            validate_non_negative_index("Y", "N", N);
            context__.validate_dims("data initialization", "Y", "int", context__.to_vec(N));
            validate_non_negative_index("Y", "N", N);
            Y = std::vector<int>(N,int(0));
            vals_i__ = context__.vals_i("Y");
            pos__ = 0;
            size_t Y_limit_0__ = N;
            for (size_t i_0__ = 0; i_0__ < Y_limit_0__; ++i_0__) {
                Y[i_0__] = vals_i__[pos__++];
            }
            current_statement_begin__ = 51;
            context__.validate_dims("data initialization", "K", "int", context__.to_vec());
            K = int(0);
            vals_i__ = context__.vals_i("K");
            pos__ = 0;
            K = vals_i__[pos__++];
            current_statement_begin__ = 52;
            validate_non_negative_index("X", "N", N);
            validate_non_negative_index("X", "K", K);
            context__.validate_dims("data initialization", "X", "matrix_d", context__.to_vec(N,K));
            validate_non_negative_index("X", "N", N);
            validate_non_negative_index("X", "K", K);
            X = matrix_d(static_cast<Eigen::VectorXd::Index>(N),static_cast<Eigen::VectorXd::Index>(K));
            vals_r__ = context__.vals_r("X");
            pos__ = 0;
            size_t X_m_mat_lim__ = N;
            size_t X_n_mat_lim__ = K;
            for (size_t n_mat__ = 0; n_mat__ < X_n_mat_lim__; ++n_mat__) {
                for (size_t m_mat__ = 0; m_mat__ < X_m_mat_lim__; ++m_mat__) {
                    X(m_mat__,n_mat__) = vals_r__[pos__++];
                }
            }
            current_statement_begin__ = 53;
            validate_non_negative_index("treat", "N", N);
            context__.validate_dims("data initialization", "treat", "int", context__.to_vec(N));
            validate_non_negative_index("treat", "N", N);
            treat = std::vector<int>(N,int(0));
            vals_i__ = context__.vals_i("treat");
            pos__ = 0;
            size_t treat_limit_0__ = N;
            for (size_t i_0__ = 0; i_0__ < treat_limit_0__; ++i_0__) {
                treat[i_0__] = vals_i__[pos__++];
            }
            current_statement_begin__ = 54;
            validate_non_negative_index("direct", "N", N);
            context__.validate_dims("data initialization", "direct", "int", context__.to_vec(N));
            validate_non_negative_index("direct", "N", N);
            direct = std::vector<int>(N,int(0));
            vals_i__ = context__.vals_i("direct");
            pos__ = 0;
            size_t direct_limit_0__ = N;
            for (size_t i_0__ = 0; i_0__ < direct_limit_0__; ++i_0__) {
                direct[i_0__] = vals_i__[pos__++];
            }
            current_statement_begin__ = 55;
            context__.validate_dims("data initialization", "G", "int", context__.to_vec());
            G = int(0);
            vals_i__ = context__.vals_i("G");
            pos__ = 0;
            G = vals_i__[pos__++];
            current_statement_begin__ = 56;
            validate_non_negative_index("h", "G", G);
            context__.validate_dims("data initialization", "h", "double", context__.to_vec(G));
            validate_non_negative_index("h", "G", G);
            h = std::vector<double>(G,double(0));
            vals_r__ = context__.vals_r("h");
            pos__ = 0;
            size_t h_limit_0__ = G;
            for (size_t i_0__ = 0; i_0__ < h_limit_0__; ++i_0__) {
                h[i_0__] = vals_r__[pos__++];
            }
            current_statement_begin__ = 57;
            validate_non_negative_index("g", "N", N);
            context__.validate_dims("data initialization", "g", "int", context__.to_vec(N));
            validate_non_negative_index("g", "N", N);
            g = std::vector<int>(N,int(0));
            vals_i__ = context__.vals_i("g");
            pos__ = 0;
            size_t g_limit_0__ = N;
            for (size_t i_0__ = 0; i_0__ < g_limit_0__; ++i_0__) {
                g[i_0__] = vals_i__[pos__++];
            }
            // validate, data variables
            current_statement_begin__ = 48;
            current_statement_begin__ = 49;
            current_statement_begin__ = 50;
            for (int k0__ = 0; k0__ < N; ++k0__) {
                check_greater_or_equal(function__,"Y[k0__]",Y[k0__],0);
            }
            current_statement_begin__ = 51;
            current_statement_begin__ = 52;
            current_statement_begin__ = 53;
            current_statement_begin__ = 54;
            current_statement_begin__ = 55;
            current_statement_begin__ = 56;
            current_statement_begin__ = 57;
            // initialize data variables
            // validate transformed data
            // validate, set parameter ranges
            num_params_r__ = 0U;
            param_ranges_i__.clear();
            current_statement_begin__ = 65;
            validate_non_negative_index("psi0", "K", K);
            num_params_r__ += K;
            current_statement_begin__ = 66;
            validate_non_negative_index("delta", "K", K);
            num_params_r__ += K;
            current_statement_begin__ = 67;
            validate_non_negative_index("gamma0", "K", K);
            num_params_r__ += K;
            current_statement_begin__ = 68;
            ++num_params_r__;
            current_statement_begin__ = 69;
            ++num_params_r__;
            current_statement_begin__ = 70;
            ++num_params_r__;
            current_statement_begin__ = 71;
            ++num_params_r__;
            current_statement_begin__ = 72;
            ++num_params_r__;
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    ~model_model_misreport_aux() { }
    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        stan::io::writer<double> writer__(params_r__,params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;
        if (!(context__.contains_r("psi0")))
            throw std::runtime_error("variable psi0 missing");
        vals_r__ = context__.vals_r("psi0");
        pos__ = 0U;
        validate_non_negative_index("psi0", "K", K);
        context__.validate_dims("initialization", "psi0", "vector_d", context__.to_vec(K));
        vector_d psi0(static_cast<Eigen::VectorXd::Index>(K));
        for (int j1__ = 0U; j1__ < K; ++j1__)
            psi0(j1__) = vals_r__[pos__++];
        try {
            writer__.vector_unconstrain(psi0);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable psi0: ") + e.what());
        }
        if (!(context__.contains_r("delta")))
            throw std::runtime_error("variable delta missing");
        vals_r__ = context__.vals_r("delta");
        pos__ = 0U;
        validate_non_negative_index("delta", "K", K);
        context__.validate_dims("initialization", "delta", "vector_d", context__.to_vec(K));
        vector_d delta(static_cast<Eigen::VectorXd::Index>(K));
        for (int j1__ = 0U; j1__ < K; ++j1__)
            delta(j1__) = vals_r__[pos__++];
        try {
            writer__.vector_unconstrain(delta);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable delta: ") + e.what());
        }
        if (!(context__.contains_r("gamma0")))
            throw std::runtime_error("variable gamma0 missing");
        vals_r__ = context__.vals_r("gamma0");
        pos__ = 0U;
        validate_non_negative_index("gamma0", "K", K);
        context__.validate_dims("initialization", "gamma0", "vector_d", context__.to_vec(K));
        vector_d gamma0(static_cast<Eigen::VectorXd::Index>(K));
        for (int j1__ = 0U; j1__ < K; ++j1__)
            gamma0(j1__) = vals_r__[pos__++];
        try {
            writer__.vector_unconstrain(gamma0);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable gamma0: ") + e.what());
        }
        if (!(context__.contains_r("treat_e")))
            throw std::runtime_error("variable treat_e missing");
        vals_r__ = context__.vals_r("treat_e");
        pos__ = 0U;
        context__.validate_dims("initialization", "treat_e", "double", context__.to_vec());
        double treat_e(0);
        treat_e = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(treat_e);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable treat_e: ") + e.what());
        }
        if (!(context__.contains_r("U_e")))
            throw std::runtime_error("variable U_e missing");
        vals_r__ = context__.vals_r("U_e");
        pos__ = 0U;
        context__.validate_dims("initialization", "U_e", "double", context__.to_vec());
        double U_e(0);
        U_e = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(U_e);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable U_e: ") + e.what());
        }
        if (!(context__.contains_r("Z_e")))
            throw std::runtime_error("variable Z_e missing");
        vals_r__ = context__.vals_r("Z_e");
        pos__ = 0U;
        context__.validate_dims("initialization", "Z_e", "double", context__.to_vec());
        double Z_e(0);
        Z_e = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(Z_e);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable Z_e: ") + e.what());
        }
        if (!(context__.contains_r("rho0")))
            throw std::runtime_error("variable rho0 missing");
        vals_r__ = context__.vals_r("rho0");
        pos__ = 0U;
        context__.validate_dims("initialization", "rho0", "double", context__.to_vec());
        double rho0(0);
        rho0 = vals_r__[pos__++];
        try {
            writer__.scalar_lub_unconstrain(0,1,rho0);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable rho0: ") + e.what());
        }
        if (!(context__.contains_r("sigma")))
            throw std::runtime_error("variable sigma missing");
        vals_r__ = context__.vals_r("sigma");
        pos__ = 0U;
        context__.validate_dims("initialization", "sigma", "double", context__.to_vec());
        double sigma(0);
        sigma = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0,sigma);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable sigma: ") + e.what());
        }
        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }
    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }
    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(vector<T__>& params_r__,
                 vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {
        typedef T__ local_scalar_t__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;
        try {
            // model parameters
            stan::io::reader<local_scalar_t__> in__(params_r__,params_i__);
            Eigen::Matrix<local_scalar_t__,Eigen::Dynamic,1>  psi0;
            (void) psi0;  // dummy to suppress unused var warning
            if (jacobian__)
                psi0 = in__.vector_constrain(K,lp__);
            else
                psi0 = in__.vector_constrain(K);
            Eigen::Matrix<local_scalar_t__,Eigen::Dynamic,1>  delta;
            (void) delta;  // dummy to suppress unused var warning
            if (jacobian__)
                delta = in__.vector_constrain(K,lp__);
            else
                delta = in__.vector_constrain(K);
            Eigen::Matrix<local_scalar_t__,Eigen::Dynamic,1>  gamma0;
            (void) gamma0;  // dummy to suppress unused var warning
            if (jacobian__)
                gamma0 = in__.vector_constrain(K,lp__);
            else
                gamma0 = in__.vector_constrain(K);
            local_scalar_t__ treat_e;
            (void) treat_e;  // dummy to suppress unused var warning
            if (jacobian__)
                treat_e = in__.scalar_constrain(lp__);
            else
                treat_e = in__.scalar_constrain();
            local_scalar_t__ U_e;
            (void) U_e;  // dummy to suppress unused var warning
            if (jacobian__)
                U_e = in__.scalar_constrain(lp__);
            else
                U_e = in__.scalar_constrain();
            local_scalar_t__ Z_e;
            (void) Z_e;  // dummy to suppress unused var warning
            if (jacobian__)
                Z_e = in__.scalar_constrain(lp__);
            else
                Z_e = in__.scalar_constrain();
            local_scalar_t__ rho0;
            (void) rho0;  // dummy to suppress unused var warning
            if (jacobian__)
                rho0 = in__.scalar_lub_constrain(0,1,lp__);
            else
                rho0 = in__.scalar_lub_constrain(0,1);
            local_scalar_t__ sigma;
            (void) sigma;  // dummy to suppress unused var warning
            if (jacobian__)
                sigma = in__.scalar_lb_constrain(0,lp__);
            else
                sigma = in__.scalar_lb_constrain(0);
            // transformed parameters
            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
            // model body
            current_statement_begin__ = 79;
            lp_accum__.add(cauchy_log<propto__>(sigma, 0, 2.5));
            current_statement_begin__ = 80;
            lp_accum__.add(normal_log<propto__>(gamma0, 0, 10));
            current_statement_begin__ = 81;
            lp_accum__.add(normal_log<propto__>(delta, 0, 10));
            current_statement_begin__ = 82;
            lp_accum__.add(normal_log<propto__>(psi0, 0, 10));
            current_statement_begin__ = 83;
            lp_accum__.add(normal_log<propto__>(treat_e, 0, 10));
            current_statement_begin__ = 84;
            lp_accum__.add(normal_log<propto__>(U_e, 0, 10));
            current_statement_begin__ = 85;
            lp_accum__.add(normal_log<propto__>(Z_e, 0, 10));
            current_statement_begin__ = 87;
            for (int gg = 1; gg <= G; ++gg) {
                current_statement_begin__ = 88;
                lp_accum__.add(normal_log<propto__>(logit(get_base1(h,gg,"h",1)), mean(multiply(subset_matrix(X,K,g,gg, pstream__),delta)), sigma));
            }
            current_statement_begin__ = 91;
            for (int i = 1; i <= N; ++i) {
                current_statement_begin__ = 93;
                if (as_bool((primitive_value(logical_eq(get_base1(treat,i,"treat",1),0)) && primitive_value(logical_eq(get_base1(direct,i,"direct",1),0))))) {
                    current_statement_begin__ = 94;
                    lp_accum__.add(stan::math::log((((stan::math::exp(jd(inv_logit(multiply(stan::model::rvalue(X, stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "X"),gamma0)), pstream__)) * stan::math::exp(gd(inv_logit(multiply(stan::model::rvalue(X, stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "X"),delta)), pstream__))) * stan::math::exp(h1d(get_base1(Y,i,"Y",1),J,((inv_logit(((multiply(stan::model::rvalue(X, stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "X"),psi0) + Z_e) + U_e)) * (1 - rho0)) / rho0),(((1 - inv_logit(((multiply(stan::model::rvalue(X, stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "X"),psi0) + Z_e) + U_e))) * (1 - rho0)) / rho0), pstream__))) + ((1 - stan::math::exp(gd(inv_logit(multiply(stan::model::rvalue(X, stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "X"),delta)), pstream__))) * stan::math::exp(h0d(get_base1(Y,i,"Y",1),J,((inv_logit(multiply(stan::model::rvalue(X, stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "X"),psi0)) * (1 - rho0)) / rho0),(((1 - inv_logit(multiply(stan::model::rvalue(X, stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "X"),psi0))) * (1 - rho0)) / rho0), pstream__))))));
                } else if (as_bool((primitive_value(logical_eq(get_base1(treat,i,"treat",1),0)) && primitive_value(logical_eq(get_base1(direct,i,"direct",1),1))))) {
                    current_statement_begin__ = 96;
                    lp_accum__.add(((stan::math::log((1 - stan::math::exp(jd(inv_logit(multiply(stan::model::rvalue(X, stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "X"),gamma0)), pstream__)))) + gd(inv_logit(multiply(stan::model::rvalue(X, stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "X"),delta)), pstream__)) + h1d(get_base1(Y,i,"Y",1),J,((inv_logit((multiply(stan::model::rvalue(X, stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "X"),psi0) + Z_e)) * (1 - rho0)) / rho0),(((1 - inv_logit((multiply(stan::model::rvalue(X, stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "X"),psi0) + Z_e))) * (1 - rho0)) / rho0), pstream__)));
                } else if (as_bool((primitive_value((primitive_value(logical_eq(get_base1(treat,i,"treat",1),1)) && primitive_value(logical_eq(get_base1(direct,i,"direct",1),0)))) && primitive_value(logical_eq(get_base1(Y,i,"Y",1),0))))) {
                    current_statement_begin__ = 98;
                    lp_accum__.add((stan::math::log((1 - stan::math::exp(gd(inv_logit(multiply(stan::model::rvalue(X, stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "X"),delta)), pstream__)))) + h0d(0,J,((inv_logit(multiply(stan::model::rvalue(X, stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "X"),psi0)) * (1 - rho0)) / rho0),(((1 - inv_logit(multiply(stan::model::rvalue(X, stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "X"),psi0))) * (1 - rho0)) / rho0), pstream__)));
                } else if (as_bool((primitive_value((primitive_value(logical_eq(get_base1(treat,i,"treat",1),1)) && primitive_value(logical_eq(get_base1(direct,i,"direct",1),0)))) && primitive_value(logical_eq(get_base1(Y,i,"Y",1),(J + 1)))))) {
                    current_statement_begin__ = 100;
                    lp_accum__.add(((jd(inv_logit((multiply(stan::model::rvalue(X, stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "X"),gamma0) + treat_e)), pstream__) + gd(inv_logit(multiply(stan::model::rvalue(X, stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "X"),delta)), pstream__)) + h1d(J,J,((inv_logit(((multiply(stan::model::rvalue(X, stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "X"),psi0) + Z_e) + U_e)) * (1 - rho0)) / rho0),(((1 - inv_logit(((multiply(stan::model::rvalue(X, stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "X"),psi0) + Z_e) + U_e))) * (1 - rho0)) / rho0), pstream__)));
                } else if (as_bool((primitive_value(logical_eq(get_base1(treat,i,"treat",1),1)) && primitive_value(logical_eq(get_base1(direct,i,"direct",1),0))))) {
                    current_statement_begin__ = 102;
                    lp_accum__.add(stan::math::log((((stan::math::exp(jd(inv_logit((multiply(stan::model::rvalue(X, stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "X"),gamma0) + treat_e)), pstream__)) * stan::math::exp(gd(inv_logit(multiply(stan::model::rvalue(X, stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "X"),delta)), pstream__))) * stan::math::exp(h1d((get_base1(Y,i,"Y",1) - 1),J,((inv_logit(((multiply(stan::model::rvalue(X, stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "X"),psi0) + Z_e) + U_e)) * (1 - rho0)) / rho0),(((1 - inv_logit(((multiply(stan::model::rvalue(X, stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "X"),psi0) + Z_e) + U_e))) * (1 - rho0)) / rho0), pstream__))) + ((1 - stan::math::exp(gd(inv_logit(multiply(stan::model::rvalue(X, stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "X"),delta)), pstream__))) * stan::math::exp(h0d(get_base1(Y,i,"Y",1),J,((inv_logit(multiply(stan::model::rvalue(X, stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "X"),psi0)) * (1 - rho0)) / rho0),(((1 - inv_logit(multiply(stan::model::rvalue(X, stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "X"),psi0))) * (1 - rho0)) / rho0), pstream__))))));
                } else if (as_bool((primitive_value((primitive_value(logical_eq(get_base1(treat,i,"treat",1),1)) && primitive_value(logical_eq(get_base1(direct,i,"direct",1),1)))) && primitive_value(logical_gt(get_base1(Y,i,"Y",1),0))))) {
                    current_statement_begin__ = 104;
                    lp_accum__.add(((stan::math::log((1 - stan::math::exp(jd(inv_logit((multiply(stan::model::rvalue(X, stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "X"),gamma0) + treat_e)), pstream__)))) + gd(inv_logit(multiply(stan::model::rvalue(X, stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "X"),delta)), pstream__)) + h1d((get_base1(Y,i,"Y",1) - 1),J,((inv_logit((multiply(stan::model::rvalue(X, stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "X"),psi0) + Z_e)) * (1 - rho0)) / rho0),(((1 - inv_logit((multiply(stan::model::rvalue(X, stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "X"),psi0) + Z_e))) * (1 - rho0)) / rho0), pstream__)));
                } else {
                    current_statement_begin__ = 106;
                    lp_accum__.add(1);
                }
            }
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
        lp_accum__.add(lp__);
        return lp_accum__.sum();
    } // log_prob()
    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }
    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("psi0");
        names__.push_back("delta");
        names__.push_back("gamma0");
        names__.push_back("treat_e");
        names__.push_back("U_e");
        names__.push_back("Z_e");
        names__.push_back("rho0");
        names__.push_back("sigma");
    }
    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dims__.push_back(K);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(K);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(K);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
    }
    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        typedef double local_scalar_t__;
        vars__.resize(0);
        stan::io::reader<local_scalar_t__> in__(params_r__,params_i__);
        static const char* function__ = "model_model_misreport_aux_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning
        // read-transform, write parameters
        vector_d psi0 = in__.vector_constrain(K);
        vector_d delta = in__.vector_constrain(K);
        vector_d gamma0 = in__.vector_constrain(K);
        double treat_e = in__.scalar_constrain();
        double U_e = in__.scalar_constrain();
        double Z_e = in__.scalar_constrain();
        double rho0 = in__.scalar_lub_constrain(0,1);
        double sigma = in__.scalar_lb_constrain(0);
            for (int k_0__ = 0; k_0__ < K; ++k_0__) {
            vars__.push_back(psi0[k_0__]);
            }
            for (int k_0__ = 0; k_0__ < K; ++k_0__) {
            vars__.push_back(delta[k_0__]);
            }
            for (int k_0__ = 0; k_0__ < K; ++k_0__) {
            vars__.push_back(gamma0[k_0__]);
            }
        vars__.push_back(treat_e);
        vars__.push_back(U_e);
        vars__.push_back(Z_e);
        vars__.push_back(rho0);
        vars__.push_back(sigma);
        // declare and define transformed parameters
        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        try {
            // validate transformed parameters
            // write transformed parameters
            if (include_tparams__) {
            }
            if (!include_gqs__) return;
            // declare and define generated quantities
            // validate generated quantities
            // write generated quantities
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng,params_r_vec,params_i_vec,vars_vec,include_tparams,include_gqs,pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }
    static std::string model_name() {
        return "model_model_misreport_aux";
    }
    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        for (int k_0__ = 1; k_0__ <= K; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "psi0" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        for (int k_0__ = 1; k_0__ <= K; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "delta" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        for (int k_0__ = 1; k_0__ <= K; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "gamma0" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "treat_e";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "U_e";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "Z_e";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "rho0";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "sigma";
        param_names__.push_back(param_name_stream__.str());
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
        }
        if (!include_gqs__) return;
    }
    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        for (int k_0__ = 1; k_0__ <= K; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "psi0" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        for (int k_0__ = 1; k_0__ <= K; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "delta" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        for (int k_0__ = 1; k_0__ <= K; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "gamma0" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "treat_e";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "U_e";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "Z_e";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "rho0";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "sigma";
        param_names__.push_back(param_name_stream__.str());
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
        }
        if (!include_gqs__) return;
    }
}; // model
}
typedef model_model_misreport_aux_namespace::model_model_misreport_aux stan_model;
#endif
