// Generated by rstantools.  Do not edit by hand.

/*
    bayeslist is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    bayeslist is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with bayeslist.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_model_outcome_doublelist_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 50> locations_array__ =
  {" (found before start of program)",
  " (in 'model_outcome_doublelist', line 28, column 1 to column 16)",
  " (in 'model_outcome_doublelist', line 29, column 1 to column 17)",
  " (in 'model_outcome_doublelist', line 30, column 1 to column 33)",
  " (in 'model_outcome_doublelist', line 35, column 2 to column 46)",
  " (in 'model_outcome_doublelist', line 36, column 2 to column 48)",
  " (in 'model_outcome_doublelist', line 34, column 15 to line 37, column 2)",
  " (in 'model_outcome_doublelist', line 34, column 1 to line 37, column 2)",
  " (in 'model_outcome_doublelist', line 39, column 1 to column 36)",
  " (in 'model_outcome_doublelist', line 48, column 3 to column 298)",
  " (in 'model_outcome_doublelist', line 47, column 9 to line 49, column 3)",
  " (in 'model_outcome_doublelist', line 46, column 3 to column 302)",
  " (in 'model_outcome_doublelist', line 45, column 27 to line 47, column 3)",
  " (in 'model_outcome_doublelist', line 45, column 9 to line 49, column 3)",
  " (in 'model_outcome_doublelist', line 44, column 3 to column 136)",
  " (in 'model_outcome_doublelist', line 43, column 44 to line 45, column 3)",
  " (in 'model_outcome_doublelist', line 43, column 9 to line 49, column 3)",
  " (in 'model_outcome_doublelist', line 42, column 3 to column 150)",
  " (in 'model_outcome_doublelist', line 41, column 34 to line 43, column 3)",
  " (in 'model_outcome_doublelist', line 41, column 2 to line 49, column 3)",
  " (in 'model_outcome_doublelist', line 40, column 15 to line 50, column 2)",
  " (in 'model_outcome_doublelist', line 40, column 1 to line 50, column 2)",
  " (in 'model_outcome_doublelist', line 14, column 1 to column 7)",
  " (in 'model_outcome_doublelist', line 15, column 1 to column 7)",
  " (in 'model_outcome_doublelist', line 16, column 18 to column 19)",
  " (in 'model_outcome_doublelist', line 16, column 1 to column 21)",
  " (in 'model_outcome_doublelist', line 17, column 1 to column 7)",
  " (in 'model_outcome_doublelist', line 18, column 8 to column 9)",
  " (in 'model_outcome_doublelist', line 18, column 10 to column 11)",
  " (in 'model_outcome_doublelist', line 18, column 1 to column 15)",
  " (in 'model_outcome_doublelist', line 19, column 11 to column 12)",
  " (in 'model_outcome_doublelist', line 19, column 1 to column 14)",
  " (in 'model_outcome_doublelist', line 20, column 14 to column 15)",
  " (in 'model_outcome_doublelist', line 20, column 1 to column 17)",
  " (in 'model_outcome_doublelist', line 21, column 28 to column 29)",
  " (in 'model_outcome_doublelist', line 21, column 1 to column 31)",
  " (in 'model_outcome_doublelist', line 22, column 15 to column 16)",
  " (in 'model_outcome_doublelist', line 22, column 1 to column 18)",
  " (in 'model_outcome_doublelist', line 23, column 29 to column 30)",
  " (in 'model_outcome_doublelist', line 23, column 1 to column 32)",
  " (in 'model_outcome_doublelist', line 24, column 1 to column 14)",
  " (in 'model_outcome_doublelist', line 25, column 1 to column 28)",
  " (in 'model_outcome_doublelist', line 28, column 8 to column 9)",
  " (in 'model_outcome_doublelist', line 29, column 8 to column 9)",
  " (in 'model_outcome_doublelist', line 4, column 2 to column 31)",
  " (in 'model_outcome_doublelist', line 3, column 16 to line 5, column 2)",
  " (in 'model_outcome_doublelist', line 7, column 2 to column 45)",
  " (in 'model_outcome_doublelist', line 6, column 46 to line 8, column 2)",
  " (in 'model_outcome_doublelist', line 10, column 2 to column 45)",
  " (in 'model_outcome_doublelist', line 9, column 46 to line 11, column 2)"};
template <typename T0__,
          stan::require_all_t<stan::is_stan_scalar<T0__>>* = nullptr>
stan::promote_args_t<T0__> gd(const T0__& p, std::ostream* pstream__);
template <typename T2__, typename T3__,
          stan::require_all_t<stan::is_stan_scalar<T2__>,
                              stan::is_stan_scalar<T3__>>* = nullptr>
stan::promote_args_t<T2__, T3__>
h0d(const int& y, const int& J, const T2__& alpha, const T3__& beta,
    std::ostream* pstream__);
template <typename T2__, typename T3__,
          stan::require_all_t<stan::is_stan_scalar<T2__>,
                              stan::is_stan_scalar<T3__>>* = nullptr>
stan::promote_args_t<T2__, T3__>
h1d(const int& y, const int& J, const T2__& alpha, const T3__& beta,
    std::ostream* pstream__);
template <typename T0__, stan::require_all_t<stan::is_stan_scalar<T0__>>*>
stan::promote_args_t<T0__> gd(const T0__& p, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__>;
  int current_statement__ = 0;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 44;
    return stan::math::binomial_lpmf<false>(1, 1, p);
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <typename T2__, typename T3__,
          stan::require_all_t<stan::is_stan_scalar<T2__>,
                              stan::is_stan_scalar<T3__>>*>
stan::promote_args_t<T2__, T3__>
h0d(const int& y, const int& J, const T2__& alpha, const T3__& beta,
    std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T2__, T3__>;
  int current_statement__ = 0;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 46;
    return stan::math::beta_binomial_lpmf<false>(y, J, alpha, beta);
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <typename T2__, typename T3__,
          stan::require_all_t<stan::is_stan_scalar<T2__>,
                              stan::is_stan_scalar<T3__>>*>
stan::promote_args_t<T2__, T3__>
h1d(const int& y, const int& J, const T2__& alpha, const T3__& beta,
    std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T2__, T3__>;
  int current_statement__ = 0;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 48;
    return stan::math::beta_binomial_lpmf<false>(y, J, alpha, beta);
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
#include <stan_meta_header.hpp>
class model_model_outcome_doublelist final : public model_base_crtp<model_model_outcome_doublelist> {
private:
  int N;
  int J;
  std::vector<int> Y;
  int K;
  Eigen::Matrix<double,-1,-1> X_data__;
  std::vector<int> treat;
  std::vector<double> mu_psi0;
  std::vector<double> sigma_psi0;
  std::vector<double> mu_delta;
  std::vector<double> sigma_delta;
  double mu_rho0;
  double sigma_rho0;
  Eigen::Map<Eigen::Matrix<double,-1,-1>> X{nullptr, 0, 0};
public:
  ~model_model_outcome_doublelist() {}
  model_model_outcome_doublelist(stan::io::var_context& context__,
                                 unsigned int random_seed__ = 0,
                                 std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_model_outcome_doublelist_namespace::model_model_outcome_doublelist";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 22;
      context__.validate_dims("data initialization", "N", "int",
        std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      current_statement__ = 22;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 23;
      context__.validate_dims("data initialization", "J", "int",
        std::vector<size_t>{});
      J = std::numeric_limits<int>::min();
      current_statement__ = 23;
      J = context__.vals_i("J")[(1 - 1)];
      current_statement__ = 24;
      stan::math::validate_non_negative_index("Y", "N", N);
      current_statement__ = 25;
      context__.validate_dims("data initialization", "Y", "int",
        std::vector<size_t>{static_cast<size_t>(N)});
      Y = std::vector<int>(N, std::numeric_limits<int>::min());
      current_statement__ = 25;
      Y = context__.vals_i("Y");
      current_statement__ = 25;
      stan::math::check_greater_or_equal(function__, "Y", Y, 0);
      current_statement__ = 26;
      context__.validate_dims("data initialization", "K", "int",
        std::vector<size_t>{});
      K = std::numeric_limits<int>::min();
      current_statement__ = 26;
      K = context__.vals_i("K")[(1 - 1)];
      current_statement__ = 27;
      stan::math::validate_non_negative_index("X", "N", N);
      current_statement__ = 28;
      stan::math::validate_non_negative_index("X", "K", K);
      current_statement__ = 29;
      context__.validate_dims("data initialization", "X", "double",
        std::vector<size_t>{static_cast<size_t>(N), static_cast<size_t>(K)});
      X_data__ = Eigen::Matrix<double,-1,-1>::Constant(N, K,
                   std::numeric_limits<double>::quiet_NaN());
      new (&X) Eigen::Map<Eigen::Matrix<double,-1,-1>>(X_data__.data(), N, K);
      {
        std::vector<local_scalar_t__> X_flat__;
        current_statement__ = 29;
        X_flat__ = context__.vals_r("X");
        current_statement__ = 29;
        pos__ = 1;
        current_statement__ = 29;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 29;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 29;
            stan::model::assign(X, X_flat__[(pos__ - 1)],
              "assigning variable X", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 29;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 30;
      stan::math::validate_non_negative_index("treat", "N", N);
      current_statement__ = 31;
      context__.validate_dims("data initialization", "treat", "int",
        std::vector<size_t>{static_cast<size_t>(N)});
      treat = std::vector<int>(N, std::numeric_limits<int>::min());
      current_statement__ = 31;
      treat = context__.vals_i("treat");
      current_statement__ = 32;
      stan::math::validate_non_negative_index("mu_psi0", "K", K);
      current_statement__ = 33;
      context__.validate_dims("data initialization", "mu_psi0", "double",
        std::vector<size_t>{static_cast<size_t>(K)});
      mu_psi0 = std::vector<double>(K,
                  std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 33;
      mu_psi0 = context__.vals_r("mu_psi0");
      current_statement__ = 34;
      stan::math::validate_non_negative_index("sigma_psi0", "K", K);
      current_statement__ = 35;
      context__.validate_dims("data initialization", "sigma_psi0", "double",
        std::vector<size_t>{static_cast<size_t>(K)});
      sigma_psi0 = std::vector<double>(K,
                     std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 35;
      sigma_psi0 = context__.vals_r("sigma_psi0");
      current_statement__ = 35;
      stan::math::check_greater_or_equal(function__, "sigma_psi0",
        sigma_psi0, 0);
      current_statement__ = 36;
      stan::math::validate_non_negative_index("mu_delta", "K", K);
      current_statement__ = 37;
      context__.validate_dims("data initialization", "mu_delta", "double",
        std::vector<size_t>{static_cast<size_t>(K)});
      mu_delta = std::vector<double>(K,
                   std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 37;
      mu_delta = context__.vals_r("mu_delta");
      current_statement__ = 38;
      stan::math::validate_non_negative_index("sigma_delta", "K", K);
      current_statement__ = 39;
      context__.validate_dims("data initialization", "sigma_delta", "double",
        std::vector<size_t>{static_cast<size_t>(K)});
      sigma_delta = std::vector<double>(K,
                      std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 39;
      sigma_delta = context__.vals_r("sigma_delta");
      current_statement__ = 39;
      stan::math::check_greater_or_equal(function__, "sigma_delta",
        sigma_delta, 0);
      current_statement__ = 40;
      context__.validate_dims("data initialization", "mu_rho0", "double",
        std::vector<size_t>{});
      mu_rho0 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 40;
      mu_rho0 = context__.vals_r("mu_rho0")[(1 - 1)];
      current_statement__ = 41;
      context__.validate_dims("data initialization", "sigma_rho0", "double",
        std::vector<size_t>{});
      sigma_rho0 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 41;
      sigma_rho0 = context__.vals_r("sigma_rho0")[(1 - 1)];
      current_statement__ = 41;
      stan::math::check_greater_or_equal(function__, "sigma_rho0",
        sigma_rho0, 0);
      current_statement__ = 42;
      stan::math::validate_non_negative_index("psi0", "K", K);
      current_statement__ = 43;
      stan::math::validate_non_negative_index("delta", "K", K);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = K + K + 1;
  }
  inline std::string model_name() const final {
    return "model_model_outcome_doublelist";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_model_outcome_doublelist_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<local_scalar_t__,-1,1> psi0 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 1;
      psi0 = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(K);
      Eigen::Matrix<local_scalar_t__,-1,1> delta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 2;
      delta = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(K);
      local_scalar_t__ rho0 = DUMMY_VAR__;
      current_statement__ = 3;
      rho0 = in__.template read_constrain_lub<local_scalar_t__,
               jacobian__>(0, 1, lp__);
      {
        current_statement__ = 7;
        for (int i = 1; i <= K; ++i) {
          current_statement__ = 4;
          lp_accum__.add(stan::math::normal_lpdf<propto__>(
                           stan::model::rvalue(psi0, "psi0",
                             stan::model::index_uni(i)),
                           stan::model::rvalue(mu_psi0, "mu_psi0",
                             stan::model::index_uni(i)),
                           stan::model::rvalue(sigma_psi0, "sigma_psi0",
                             stan::model::index_uni(i))));
          current_statement__ = 5;
          lp_accum__.add(stan::math::normal_lpdf<propto__>(
                           stan::model::rvalue(delta, "delta",
                             stan::model::index_uni(i)),
                           stan::model::rvalue(mu_delta, "mu_delta",
                             stan::model::index_uni(i)),
                           stan::model::rvalue(sigma_delta, "sigma_delta",
                             stan::model::index_uni(i))));
        }
        current_statement__ = 8;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(rho0, mu_rho0,
                         sigma_rho0));
        current_statement__ = 21;
        for (int i = 1; i <= N; ++i) {
          current_statement__ = 19;
          if ((stan::math::primitive_value(
                 stan::math::logical_eq(
                   stan::model::rvalue(treat, "treat",
                     stan::model::index_uni(i)), 1))
              &&
              stan::math::primitive_value(
                stan::math::logical_eq(
                  stan::model::rvalue(Y, "Y", stan::model::index_uni(i)), 0)))) {
            current_statement__ = 17;
            lp_accum__.add((stan::math::log((1 -
                              stan::math::exp(
                                gd(
                                  stan::math::inv_logit(
                                    stan::math::multiply(
                                      stan::model::rvalue(X, "X",
                                        stan::model::index_uni(i),
                                        stan::model::index_omni()), delta)),
                                  pstream__)))) +
              h0d(0, J,
                ((stan::math::inv_logit(
                    stan::math::multiply(
                      stan::model::rvalue(X, "X", stan::model::index_uni(i),
                        stan::model::index_omni()), psi0)) * (1 - rho0)) /
                rho0), (((1 -
                stan::math::inv_logit(
                  stan::math::multiply(
                    stan::model::rvalue(X, "X", stan::model::index_uni(i),
                      stan::model::index_omni()), psi0))) * (1 - rho0)) /
                rho0), pstream__)));
          } else {
            current_statement__ = 16;
            if ((stan::math::primitive_value(
                   stan::math::logical_eq(
                     stan::model::rvalue(treat, "treat",
                       stan::model::index_uni(i)), 1))
                &&
                stan::math::primitive_value(
                  stan::math::logical_eq(
                    stan::model::rvalue(Y, "Y", stan::model::index_uni(i)),
                    (J + 1))))) {
              current_statement__ = 14;
              lp_accum__.add((gd(
                                stan::math::inv_logit(
                                  stan::math::multiply(
                                    stan::model::rvalue(X, "X",
                                      stan::model::index_uni(i),
                                      stan::model::index_omni()), delta)),
                                pstream__) +
                h1d(J, J,
                  ((stan::math::inv_logit(
                      stan::math::multiply(
                        stan::model::rvalue(X, "X",
                          stan::model::index_uni(i),
                          stan::model::index_omni()), psi0)) * (1 - rho0)) /
                  rho0), (((1 -
                  stan::math::inv_logit(
                    stan::math::multiply(
                      stan::model::rvalue(X, "X", stan::model::index_uni(i),
                        stan::model::index_omni()), psi0))) * (1 - rho0)) /
                  rho0), pstream__)));
            } else {
              current_statement__ = 13;
              if (stan::math::logical_eq(
                    stan::model::rvalue(treat, "treat",
                      stan::model::index_uni(i)), 1)) {
                current_statement__ = 11;
                lp_accum__.add(stan::math::log(
                                 ((stan::math::exp(
                                     gd(
                                       stan::math::inv_logit(
                                         stan::math::multiply(
                                           stan::model::rvalue(X, "X",
                                             stan::model::index_uni(i),
                                             stan::model::index_omni()),
                                           delta)), pstream__)) *
                                 stan::math::exp(
                                   h1d(
                                     (stan::model::rvalue(Y, "Y",
                                        stan::model::index_uni(i)) - 1), J,
                                     ((stan::math::inv_logit(
                                         stan::math::multiply(
                                           stan::model::rvalue(X, "X",
                                             stan::model::index_uni(i),
                                             stan::model::index_omni()), psi0))
                                     * (1 - rho0)) / rho0), (((1 -
                                     stan::math::inv_logit(
                                       stan::math::multiply(
                                         stan::model::rvalue(X, "X",
                                           stan::model::index_uni(i),
                                           stan::model::index_omni()), psi0)))
                                     * (1 - rho0)) / rho0), pstream__))) +
                                 ((1 -
                                 stan::math::exp(
                                   gd(
                                     stan::math::inv_logit(
                                       stan::math::multiply(
                                         stan::model::rvalue(X, "X",
                                           stan::model::index_uni(i),
                                           stan::model::index_omni()), delta)),
                                     pstream__))) *
                                 stan::math::exp(
                                   h0d(
                                     stan::model::rvalue(Y, "Y",
                                       stan::model::index_uni(i)), J,
                                     ((stan::math::inv_logit(
                                         stan::math::multiply(
                                           stan::model::rvalue(X, "X",
                                             stan::model::index_uni(i),
                                             stan::model::index_omni()), psi0))
                                     * (1 - rho0)) / rho0), (((1 -
                                     stan::math::inv_logit(
                                       stan::math::multiply(
                                         stan::model::rvalue(X, "X",
                                           stan::model::index_uni(i),
                                           stan::model::index_omni()), psi0)))
                                     * (1 - rho0)) / rho0), pstream__))))));
              } else {
                current_statement__ = 9;
                lp_accum__.add(stan::math::log(
                                 ((stan::math::exp(
                                     gd(
                                       stan::math::inv_logit(
                                         stan::math::multiply(
                                           stan::model::rvalue(X, "X",
                                             stan::model::index_uni(i),
                                             stan::model::index_omni()),
                                           delta)), pstream__)) *
                                 stan::math::exp(
                                   h1d(
                                     stan::model::rvalue(Y, "Y",
                                       stan::model::index_uni(i)), J,
                                     ((stan::math::inv_logit(
                                         stan::math::multiply(
                                           stan::model::rvalue(X, "X",
                                             stan::model::index_uni(i),
                                             stan::model::index_omni()), psi0))
                                     * (1 - rho0)) / rho0), (((1 -
                                     stan::math::inv_logit(
                                       stan::math::multiply(
                                         stan::model::rvalue(X, "X",
                                           stan::model::index_uni(i),
                                           stan::model::index_omni()), psi0)))
                                     * (1 - rho0)) / rho0), pstream__))) +
                                 ((1 -
                                 stan::math::exp(
                                   gd(
                                     stan::math::inv_logit(
                                       stan::math::multiply(
                                         stan::model::rvalue(X, "X",
                                           stan::model::index_uni(i),
                                           stan::model::index_omni()), delta)),
                                     pstream__))) *
                                 stan::math::exp(
                                   h0d(
                                     stan::model::rvalue(Y, "Y",
                                       stan::model::index_uni(i)), J,
                                     ((stan::math::inv_logit(
                                         stan::math::multiply(
                                           stan::model::rvalue(X, "X",
                                             stan::model::index_uni(i),
                                             stan::model::index_omni()), psi0))
                                     * (1 - rho0)) / rho0), (((1 -
                                     stan::math::inv_logit(
                                       stan::math::multiply(
                                         stan::model::rvalue(X, "X",
                                           stan::model::index_uni(i),
                                           stan::model::index_omni()), psi0)))
                                     * (1 - rho0)) / rho0), pstream__))))));
              }
            }
          }
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_model_outcome_doublelist_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<double,-1,1> psi0 =
        Eigen::Matrix<double,-1,1>::Constant(K,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 1;
      psi0 = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(K);
      Eigen::Matrix<double,-1,1> delta =
        Eigen::Matrix<double,-1,1>::Constant(K,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 2;
      delta = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(K);
      double rho0 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 3;
      rho0 = in__.template read_constrain_lub<local_scalar_t__,
               jacobian__>(0, 1, lp__);
      out__.write(psi0);
      out__.write(delta);
      out__.write(rho0);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> psi0 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 1;
      stan::model::assign(psi0,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(K),
        "assigning variable psi0");
      out__.write(psi0);
      Eigen::Matrix<local_scalar_t__,-1,1> delta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 2;
      stan::model::assign(delta,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(K),
        "assigning variable delta");
      out__.write(delta);
      local_scalar_t__ rho0 = DUMMY_VAR__;
      current_statement__ = 3;
      rho0 = in__.read<local_scalar_t__>();
      out__.write_free_lub(0, 1, rho0);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "psi0", "double",
        std::vector<size_t>{static_cast<size_t>(K)});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "delta", "double",
        std::vector<size_t>{static_cast<size_t>(K)});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "rho0", "double",
        std::vector<size_t>{});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> psi0 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> psi0_flat__;
        current_statement__ = 1;
        psi0_flat__ = context__.vals_r("psi0");
        current_statement__ = 1;
        pos__ = 1;
        current_statement__ = 1;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 1;
          stan::model::assign(psi0, psi0_flat__[(pos__ - 1)],
            "assigning variable psi0", stan::model::index_uni(sym1__));
          current_statement__ = 1;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(psi0);
      Eigen::Matrix<local_scalar_t__,-1,1> delta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> delta_flat__;
        current_statement__ = 2;
        delta_flat__ = context__.vals_r("delta");
        current_statement__ = 2;
        pos__ = 1;
        current_statement__ = 2;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 2;
          stan::model::assign(delta, delta_flat__[(pos__ - 1)],
            "assigning variable delta", stan::model::index_uni(sym1__));
          current_statement__ = 2;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(delta);
      local_scalar_t__ rho0 = DUMMY_VAR__;
      current_statement__ = 3;
      rho0 = context__.vals_r("rho0")[(1 - 1)];
      out__.write_free_lub(0, 1, rho0);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"psi0", "delta", "rho0"};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{static_cast<
                                                                    size_t>(K)},
                std::vector<size_t>{static_cast<size_t>(K)},
                std::vector<size_t>{}};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      param_names__.emplace_back(std::string() + "psi0" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      param_names__.emplace_back(std::string() + "delta" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "rho0");
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      param_names__.emplace_back(std::string() + "psi0" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      param_names__.emplace_back(std::string() + "delta" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "rho0");
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"psi0\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"delta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"rho0\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"psi0\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"delta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"rho0\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((K + K) + 1);
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((K + K) + 1);
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_model_outcome_doublelist_namespace::model_model_outcome_doublelist;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_model_outcome_doublelist_namespace::profiles__;
}
#endif
#endif
