# Generated by rstantools.  Do not edit by hand.

# names of stan models
stanmodels <- c("model_misreport_aux", "model_misreport_cmp", "model_misreport_doublelist", "model_misreport_infonorm", "model_misreport_noaux", "model_outcome_aux", "model_outcome_cmp", "model_outcome_doublelist", "model_outcome_infonorm", "model_outcome_noaux", "model_predict_aux", "model_predict_aux_linear", "model_predict_cmp", "model_predict_cmp_linear", "model_predict_doublelist", "model_predict_doublelist_linear", "model_predict_infonorm", "model_predict_infonorm_linear", "model_predict_noaux", "model_predict_noaux_linear")

# load each stan module
Rcpp::loadModule("stan_fit4model_misreport_aux_mod", what = TRUE)
Rcpp::loadModule("stan_fit4model_misreport_cmp_mod", what = TRUE)
Rcpp::loadModule("stan_fit4model_misreport_doublelist_mod", what = TRUE)
Rcpp::loadModule("stan_fit4model_misreport_infonorm_mod", what = TRUE)
Rcpp::loadModule("stan_fit4model_misreport_noaux_mod", what = TRUE)
Rcpp::loadModule("stan_fit4model_outcome_aux_mod", what = TRUE)
Rcpp::loadModule("stan_fit4model_outcome_cmp_mod", what = TRUE)
Rcpp::loadModule("stan_fit4model_outcome_doublelist_mod", what = TRUE)
Rcpp::loadModule("stan_fit4model_outcome_infonorm_mod", what = TRUE)
Rcpp::loadModule("stan_fit4model_outcome_noaux_mod", what = TRUE)
Rcpp::loadModule("stan_fit4model_predict_aux_mod", what = TRUE)
Rcpp::loadModule("stan_fit4model_predict_aux_linear_mod", what = TRUE)
Rcpp::loadModule("stan_fit4model_predict_cmp_mod", what = TRUE)
Rcpp::loadModule("stan_fit4model_predict_cmp_linear_mod", what = TRUE)
Rcpp::loadModule("stan_fit4model_predict_doublelist_mod", what = TRUE)
Rcpp::loadModule("stan_fit4model_predict_doublelist_linear_mod", what = TRUE)
Rcpp::loadModule("stan_fit4model_predict_infonorm_mod", what = TRUE)
Rcpp::loadModule("stan_fit4model_predict_infonorm_linear_mod", what = TRUE)
Rcpp::loadModule("stan_fit4model_predict_noaux_mod", what = TRUE)
Rcpp::loadModule("stan_fit4model_predict_noaux_linear_mod", what = TRUE)

# instantiate each stanmodel object
stanmodels <- sapply(stanmodels, function(model_name) {
  # create C++ code for stan model
  stan_file <- if(dir.exists("stan")) "stan" else file.path("inst", "stan")
  stan_file <- file.path(stan_file, paste0(model_name, ".stan"))
  stanfit <- rstan::stanc_builder(stan_file,
                                  allow_undefined = TRUE,
                                  obfuscate_model_name = FALSE)
  stanfit$model_cpp <- list(model_cppname = stanfit$model_name,
                            model_cppcode = stanfit$cppcode)
  # create stanmodel object
  methods::new(Class = "stanmodel",
               model_name = stanfit$model_name,
               model_code = stanfit$model_code,
               model_cpp = stanfit$model_cpp,
               mk_cppmodule = function(x) get(paste0("rstantools_model_", model_name)))
})
